/* Generated by Cython 0.29.34 */

#ifndef __PYX_HAVE__minimize_thomson
#define __PYX_HAVE__minimize_thomson

#include "Python.h"

#ifndef __PYX_HAVE_API__minimize_thomson

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void PyInit_minimize_thomson(void);

#endif /* !__PYX_HAVE_API__minimize_thomson */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initminimize_thomson(void);
#else
PyMODINIT_FUNC PyInit_minimize_thomson(void);
#endif

#endif /* !__PYX_HAVE__minimize_thomson */
